### ISSUE TITLE
summernote-rails 0.8.1.1 breaks test environment with error: undefined method `[]' for nil:NilClass

### ISSUE THREAD

**Issue by mattbrictson** [summernote/summernote-rails#46]
Hi, I just upgraded from summernote-rails 0.7.1.0 to 0.8.1.1 and my capybara tests are now all failing. I am just digging into this now and will try to build a more concise failure case, but perhaps someone watching these issues has encountered the same problem and has some ideas?

Here is the error:

```
ActionView::Template::Error: undefined method `[]' for nil:NilClass
sprockets-3.5.2/lib/sprockets/sass_processor.rb:278:in `sprockets_context'
```

**Removing `//= require summernote` from my `application.css.scss` fixes the problem.** Downgrading to summernote-rails 0.7.1.0 also fixes it.

The failing code in `sprockets-3.5.2/lib/sprockets/sass_processor.rb` is:

```ruby
def sprockets_context
  options[:sprockets][:context] # Fails here
end
```

Using pry I discovered that `options` has no key named `:sprockets`, and so `options[:sprockets]` is nil, leading to the error.

I am using Rails 4.2.5.1, sprockets 3.5.2, sprockets-rails 3.0.2, and summernote-rails 0.8.1.1.

Here is a more complete backtrace:

```
sprockets-3.5.2/lib/sprockets/sass_processor.rb:280:in `sprockets_context'
sprockets-3.5.2/lib/sprockets/sass_processor.rb:124:in `asset_path'
sprockets-3.5.2/lib/sprockets/sass_processor.rb:200:in `font_path'
sass-3.4.21/lib/sass/script/tree/funcall.rb:140:in `_perform'
sass-3.4.21/lib/sass/script/tree/node.rb:50:in `perform'
sass-3.4.21/lib/sass/script/tree/funcall.rb:170:in `perform_arg'
sass-3.4.21/lib/sass/script/tree/funcall.rb:124:in `block in _perform'
sass-3.4.21/lib/sass/script/tree/funcall.rb:124:in `each'
sass-3.4.21/lib/sass/script/tree/funcall.rb:124:in `each_with_index'
sass-3.4.21/lib/sass/script/tree/funcall.rb:124:in `each'
sass-3.4.21/lib/sass/script/tree/funcall.rb:124:in `map'
sass-3.4.21/lib/sass/script/tree/funcall.rb:124:in `_perform'
sass-3.4.21/lib/sass/script/tree/node.rb:50:in `perform'
sass-3.4.21/lib/sass/tree/visitors/perform.rb:395:in `visit_prop'
sass-3.4.21/lib/sass/tree/visitors/base.rb:36:in `visit'
sass-3.4.21/lib/sass/tree/visitors/perform.rb:158:in `block in visit'
sass-3.4.21/lib/sass/stack.rb:79:in `block in with_base'
sass-3.4.21/lib/sass/stack.rb:115:in `with_frame'
sass-3.4.21/lib/sass/stack.rb:79:in `with_base'
sass-3.4.21/lib/sass/tree/visitors/perform.rb:158:in `visit'
sass-3.4.21/lib/sass/tree/visitors/perform.rb:502:in `block (2 levels) in visit_directive'
sass-3.4.21/lib/sass/tree/visitors/perform.rb:502:in `map'
sass-3.4.21/lib/sass/tree/visitors/perform.rb:502:in `block in visit_directive'
sass-3.4.21/lib/sass/tree/visitors/perform.rb:179:in `with_environment'
sass-3.4.21/lib/sass/tree/visitors/perform.rb:501:in `visit_directive'
sass-3.4.21/lib/sass/tree/visitors/base.rb:36:in `visit'
sass-3.4.21/lib/sass/tree/visitors/perform.rb:158:in `block in visit'
sass-3.4.21/lib/sass/stack.rb:79:in `block in with_base'
sass-3.4.21/lib/sass/stack.rb:115:in `with_frame'
sass-3.4.21/lib/sass/stack.rb:79:in `with_base'
sass-3.4.21/lib/sass/tree/visitors/perform.rb:158:in `visit'
sass-3.4.21/lib/sass/tree/visitors/base.rb:52:in `block in visit_children'
sass-3.4.21/lib/sass/tree/visitors/base.rb:52:in `map'
sass-3.4.21/lib/sass/tree/visitors/base.rb:52:in `visit_children'
sass-3.4.21/lib/sass/tree/visitors/perform.rb:167:in `block in visit_children'
sass-3.4.21/lib/sass/tree/visitors/perform.rb:179:in `with_environment'
sass-3.4.21/lib/sass/tree/visitors/perform.rb:166:in `visit_children'
sass-3.4.21/lib/sass/tree/visitors/base.rb:36:in `block in visit'
sass-3.4.21/lib/sass/tree/visitors/perform.rb:186:in `visit_root'
sass-3.4.21/lib/sass/tree/visitors/base.rb:36:in `visit'
sass-3.4.21/lib/sass/tree/visitors/perform.rb:157:in `visit'
sass-3.4.21/lib/sass/tree/visitors/perform.rb:8:in `visit'
sass-3.4.21/lib/sass/tree/root_node.rb:36:in `css_tree'
sass-3.4.21/lib/sass/tree/root_node.rb:20:in `render'
sass-3.4.21/lib/sass/engine.rb:278:in `render'
sprockets-3.5.2/lib/sprockets/sass_compressor.rb:48:in `call'
sprockets-3.5.2/lib/sprockets/sass_compressor.rb:28:in `call'
sprockets-3.5.2/lib/sprockets/processor_utils.rb:75:in `call_processor'
sprockets-3.5.2/lib/sprockets/processor_utils.rb:57:in `block in call_processors'
sprockets-3.5.2/lib/sprockets/processor_utils.rb:56:in `reverse_each'
sprockets-3.5.2/lib/sprockets/processor_utils.rb:56:in `call_processors'
sprockets-3.5.2/lib/sprockets/loader.rb:134:in `load_from_unloaded'
sprockets-3.5.2/lib/sprockets/loader.rb:60:in `block in load'
sprockets-3.5.2/lib/sprockets/loader.rb:318:in `fetch_asset_from_dependency_cache'
sprockets-3.5.2/lib/sprockets/loader.rb:44:in `load'
sprockets-3.5.2/lib/sprockets/cached_environment.rb:20:in `block in initialize'
sprockets-3.5.2/lib/sprockets/cached_environment.rb:47:in `load'
sprockets-3.5.2/lib/sprockets/base.rb:66:in `find_asset'
sprockets-3.5.2/lib/sprockets/base.rb:73:in `find_all_linked_assets'
sprockets-3.5.2/lib/sprockets/manifest.rb:142:in `block in find'
sprockets-3.5.2/lib/sprockets/legacy.rb:114:in `block (2 levels) in logical_paths'
sprockets-3.5.2/lib/sprockets/path_utils.rb:225:in `block in stat_tree'
sprockets-3.5.2/lib/sprockets/path_utils.rb:209:in `block in stat_directory'
sprockets-3.5.2/lib/sprockets/path_utils.rb:206:in `each'
sprockets-3.5.2/lib/sprockets/path_utils.rb:206:in `stat_directory'
sprockets-3.5.2/lib/sprockets/path_utils.rb:224:in `stat_tree'
sprockets-3.5.2/lib/sprockets/legacy.rb:105:in `each'
sprockets-3.5.2/lib/sprockets/legacy.rb:105:in `block in logical_paths'
sprockets-3.5.2/lib/sprockets/legacy.rb:104:in `each'
sprockets-3.5.2/lib/sprockets/legacy.rb:104:in `logical_paths'
sprockets-3.5.2/lib/sprockets/manifest.rb:140:in `find'
sprockets-rails-3.0.2/lib/sprockets/railtie.rb:41:in `each'
sprockets-rails-3.0.2/lib/sprockets/railtie.rb:41:in `map'
sprockets-rails-3.0.2/lib/sprockets/railtie.rb:41:in `precompiled_assets'
sprockets-rails-3.0.2/lib/sprockets/railtie.rb:34:in `asset_precompiled?'
sprockets-rails-3.0.2/lib/sprockets/railtie.rb:205:in `block (3 levels) in <class:Railtie>'
sprockets-rails-3.0.2/lib/sprockets/rails/helper.rb:346:in `precompiled?'
sprockets-rails-3.0.2/lib/sprockets/rails/helper.rb:350:in `raise_unless_precompiled_asset'
sprockets-rails-3.0.2/lib/sprockets/rails/helper.rb:324:in `digest_path'
sprockets-rails-3.0.2/lib/sprockets/rails/helper.rb:312:in `asset_path'
sprockets-rails-3.0.2/lib/sprockets/rails/helper.rb:90:in `block in resolve_asset_path'
sprockets-rails-3.0.2/lib/sprockets/rails/helper.rb:230:in `block in resolve_asset'
sprockets-rails-3.0.2/lib/sprockets/rails/helper.rb:229:in `each'
sprockets-rails-3.0.2/lib/sprockets/rails/helper.rb:229:in `detect'
sprockets-rails-3.0.2/lib/sprockets/rails/helper.rb:229:in `resolve_asset'
sprockets-rails-3.0.2/lib/sprockets/rails/helper.rb:89:in `resolve_asset_path'
sprockets-rails-3.0.2/lib/sprockets/rails/helper.rb:79:in `compute_asset_path'
actionview-4.2.5.1/lib/action_view/helpers/asset_url_helper.rb:135:in `asset_path'
actionview-4.2.5.1/lib/action_view/helpers/asset_url_helper.rb:267:in `stylesheet_path'
actionview-4.2.5.1/lib/action_view/helpers/asset_tag_helper.rb:100:in `block in stylesheet_link_tag'
actionview-4.2.5.1/lib/action_view/helpers/asset_tag_helper.rb:96:in `map'
actionview-4.2.5.1/lib/action_view/helpers/asset_tag_helper.rb:96:in `stylesheet_link_tag'
sprockets-rails-3.0.2/lib/sprockets/rails/helper.rb:173:in `block in stylesheet_link_tag'
sprockets-rails-3.0.2/lib/sprockets/rails/helper.rb:171:in `map'
sprockets-rails-3.0.2/lib/sprockets/rails/helper.rb:171:in `stylesheet_link_tag'
```

**Comment by mattbrictson** [comment]
OK, it looks like if I use `@import "summernote"` instead of the Sprockets-style manifest `//= require summernote`, then the problem goes away.

**Comment by Faisal-nfl** [comment]
but with @import "summernote"
it doesn't work

**Comment by JIAZHEN** [comment]
I am pretty sure this is still an issue.

**Comment by Ricardonacif** [comment]
We're facing this as well
